"""
generate_san_configs.py
========================
Writes configs/san/san_<pe>_<dataset>.json for all 5 PEs x 3 datasets, from
backends.san_backend's own PE_SPEC / BASE_NET_PARAMS / TRAIN_PARAMS.

Why generated rather than hand-written
---------------------------------------
The previous configs/san/*.json (from before the real backend existed) hardcoded values
like `"grpe_num_spd_buckets": 24` that were correct on the day they were written and had no
mechanism to notice when dataset_meta.SPD_NUM_BUCKETS changed later -- exactly the kind of
silent drift PE_CACHE_VERSION and the pinned-commit checks elsewhere in this project exist
to catch. Generating from the single source of truth in san_backend.py means a config file
can only be as stale as this script, which is cheap to re-run.

Usage:
    python scripts/generate_san_configs.py            # regenerate all 15
    python scripts/generate_san_configs.py --check     # exit 1 if any file would change
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
from backends.san_backend import BASE_NET_PARAMS, PE_SPEC, TRAIN_PARAMS  # noqa: E402
from config import DATASETS, PES  # noqa: E402
from dataset_meta import SPD_NUM_BUCKETS  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "configs", "san")


def build_one(pe: str, dataset: str) -> dict:
    return {
        "_comment": (
            f"SAN config: PE={pe}, dataset={dataset}. Generated by "
            "scripts/generate_san_configs.py from backends/san_backend.py's PE_SPEC / "
            "BASE_NET_PARAMS / TRAIN_PARAMS -- do not hand-edit, re-run the generator "
            "after changing those. NOT upstream-tuned: SAN's own repo ships no LRGB "
            "reference configs (see san_backend.py's module docstring, consequence 1)."
        ),
        "pe": pe,
        "dataset": dataset,
        "params": dict(TRAIN_PARAMS),
        "net_params": {**PE_SPEC[pe], **({"grpe_num_spd_buckets": SPD_NUM_BUCKETS}
                                          if pe == "grpe" else {})},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if regenerating would change any file, write nothing")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    changed = []
    for dataset in DATASETS:
        if dataset not in BASE_NET_PARAMS:
            continue
        for pe in PES:
            path = os.path.join(OUT_DIR, f"san_{pe}_{dataset}.json")
            new_content = json.dumps(build_one(pe, dataset), indent=2) + "\n"
            old_content = open(path).read() if os.path.exists(path) else None
            if new_content != old_content:
                changed.append(path)
                if not args.check:
                    with open(path, "w") as f:
                        f.write(new_content)

    if args.check:
        if changed:
            print("Stale or missing configs:\n  " + "\n  ".join(changed))
            sys.exit(1)
        print("All SAN configs up to date.")
    else:
        print(f"Wrote {len(changed)} changed file(s); "
              f"{15 - len(changed)} were already up to date.")


if __name__ == "__main__":
    main()
