"""
make_paper_tables.py
=====================
Turns results_all/summary_table.csv + results_all/criterion_b_*.csv (produced by
`collect_cross_backbone_results.py` + `aggregate_results.py` run across all three
backbone branches) into the literal LaTeX fragments used in Section 5 of
paper_ACL_format.tex.

Run:
    python scripts/collect_cross_backbone_results.py --out results_all
    python scripts/aggregate_results.py --results-dir results_all
    python scripts/make_paper_tables.py --in-dir results_all --out results_all/paper_fragments.tex

Every number this script emits is one of exactly three kinds, and each block below is
labelled with which:
  [PER-CELL, SEEDS POOLED]   one (backbone, pe, dataset) cell, mean+-std OVER SEEDS,
                             rho/rho_rel pooled over all seeds' test graphs together
                             (graph-clustered bootstrap CI; see docs/analysis-plan.md
                             Amendment 2 for why seeds are pooled rather than averaged).
  [PER-BACKBONE, PES POOLED] one backbone x dataset, Spearman rho_rel-vs-metric rank
                             correlation over its (up to 5) PE arms -- n is small (<=5)
                             and each such row is DESCRIPTIVE ONLY (analysis-plan.md
                             Amendment 3).
  [POOLED ACROSS BACKBONES]  the "ALL (pooled)" row: every (backbone, PE) arm for a
                             dataset in one Spearman test -- this is the CONFIRMATORY
                             test for criterion (b), per Amendment 3.
Nothing here is pooled across DATASETS -- the three tasks/graph regimes are kept
separate throughout, since that separation is the entire point of the expanded design.
"""
import argparse
import os

import pandas as pd

DATASET_LABEL = {
    "peptides-func": "Peptides-func",
    "peptides-struct": "Peptides-struct",
    "pascalvoc-sp": "PascalVOC-SP",
}
METRIC_LABEL = {
    "peptides-func": ("AP", True),
    "peptides-struct": ("MAE", False),
    "pascalvoc-sp": ("macro-F1", True),
}
BACKBONE_LABEL = {"gps": "GraphGPS", "san": "SAN", "graphormer": "Graphormer"}
PE_ORDER = ["none", "lappe", "rwse", "signnet", "grpe"]
PE_LABEL = {"none": "No-PE", "lappe": "LapPE", "rwse": "RWSE",
            "signnet": "SignNet-PE", "grpe": "GRPE"}


def fmt(x, nd=4):
    return "--" if pd.isna(x) else f"{x:.{nd}f}"


def significant(row, none_row):
    """CI-disjoint-from-none AND seed_std doesn't dominate the gap -- the exact rule
    findings_gps.txt Sec. 8 insists on: never call an effect from the CI alone."""
    if none_row is None or pd.isna(row.rho_rel_ci_lo) or pd.isna(none_row.rho_rel_ci_lo):
        return False
    disjoint = (row.rho_rel_ci_lo > none_row.rho_rel_ci_hi) or (row.rho_rel_ci_hi < none_row.rho_rel_ci_lo)
    gap = abs(row.rho_rel - none_row.rho_rel)
    seed_noise = max(row.get("rho_seed_std", 0) or 0, none_row.get("rho_seed_std", 0) or 0)
    return bool(disjoint and gap > seed_noise)


def _iter_rows(df):
    """Shared row order for both split tables: (dataset, backbone) pairs, same
    order Table 3a/3b and the reader both walk through."""
    for ds in ["peptides-func", "peptides-struct", "pascalvoc-sp"]:
        sub = df[df.dataset == ds]
        if sub.empty:
            continue
        for backbone in ["gps", "graphormer", "san"]:
            bsub = sub[sub.backbone == backbone]
            if bsub.empty:
                continue
            none_row = bsub[bsub.pe == "none"].iloc[0] if (bsub.pe == "none").any() else None
            yield ds, backbone, bsub, none_row


def _seed_count_caption_clause(df):
    """Never hand-write which cells have fewer seeds -- state it from the data,
    so a re-run (e.g. after a backbone branch fills in a previously-missing
    seed) can't silently leave a stale exception in the caption."""
    short = df[df.n_seeds < 3]
    if short.empty:
        return "3 throughout"
    exceptions = ", ".join(
        f"{BACKBONE_LABEL[b]} {DATASET_LABEL[d]} {PE_LABEL[p]}: {int(n)}"
        for b, p, d, n in short[["backbone", "pe", "dataset", "n_seeds"]].itertuples(index=False)
    )
    return f"3 except {exceptions}"


def build_metric_table(df):
    """[PER-CELL, SEEDS POOLED] Table 3a: task metric only, one row per
    (dataset, backbone), one column per PE. Split out of the old combined
    metric+rho_rel table (each cell used to stack both via \\shortstack) so a
    reader reads one number per cell instead of two stacked ones -- same row
    order as Table 3b (build_rho_table) so the two are read side by side."""
    lines = [r"% Auto-generated by scripts/make_paper_tables.py -- do not hand-edit.",
             r"% Table 3a: task metric only (mean over completed seeds). Same",
             r"% row order as Table 3b (rho_rel) -- read the two side by side.",
             r"\begin{table*}[t]", r"\centering\footnotesize",
             r"\setlength{\tabcolsep}{4pt}"]
    pes = PE_ORDER
    lines.append(r"\begin{tabular}{ll" + "c" * len(pes) + "}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Dataset} & \textbf{Backbone} & " +
                 " & ".join(f"\\textbf{{{PE_LABEL[p]}}}" for p in pes) + r" \\")
    lines.append(r"\midrule")
    for ds, backbone, bsub, _ in _iter_rows(df):
        metric_name, _ = METRIC_LABEL[ds]
        cells = []
        for p in pes:
            match = bsub[bsub.pe == p]
            cells.append(fmt(match.iloc[0].metric_mean, 3) if not match.empty else "--")
        lines.append(f"{DATASET_LABEL[ds]} & {BACKBONE_LABEL[backbone]} & " +
                     " & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        rf"\caption{{Task metric (mean over completed seeds; {_seed_count_caption_clause(df)}) "
        r"per (dataset, backbone, PE) cell -- AP/macro-F1 higher is "
        r"better, MAE lower is better (Table~\ref{tab:data}). `--' = never trained (\S3). "
        r"$\rho_{\text{rel}}$ for the same cells is Table~\ref{tab:rho}.}"
    )
    lines.append(r"\label{tab:results}")
    lines.append(r"\end{table*}")
    return "\n".join(lines)


def build_rho_table(df):
    """[PER-CELL, SEEDS POOLED] Table 3b: rho_rel only, same row/column order as
    Table 3a (build_metric_table). rho_rel is pooled over ALL of that cell's
    seeds' test graphs (graph-clustered bootstrap), never averaged per-seed."""
    lines = [r"% Auto-generated by scripts/make_paper_tables.py -- do not hand-edit.",
             r"% Table 3b: rho_rel only, pooled over all seeds' test graphs (graph-",
             r"% clustered bootstrap). Same row order as Table 3a (task metric).",
             r"\begin{table*}[t]", r"\centering\footnotesize",
             r"\setlength{\tabcolsep}{4pt}"]
    pes = PE_ORDER
    lines.append(r"\begin{tabular}{ll" + "c" * len(pes) + "}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Dataset} & \textbf{Backbone} & " +
                 " & ".join(f"\\textbf{{{PE_LABEL[p]}}}" for p in pes) + r" \\")
    lines.append(r"\midrule")
    for ds, backbone, bsub, none_row in _iter_rows(df):
        cells = []
        for p in pes:
            match = bsub[bsub.pe == p]
            if match.empty:
                cells.append("--")
                continue
            row = match.iloc[0]
            star = r"$^{*}$" if (p != "none" and significant(row, none_row)) else ""
            cells.append(f"{fmt(row.rho_rel)}{star}")
        lines.append(f"{DATASET_LABEL[ds]} & {BACKBONE_LABEL[backbone]} & " +
                     " & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        r"\caption{$\rho_{\text{rel}}$, the relative long-range mass fraction "
        r"($d/\mathrm{diam}(G)>0.5$; docs/analysis-plan.md Amendment 5), for the same "
        r"cells as Table~\ref{tab:results}. $^{*}$ = CI disjoint from that row's No-PE "
        r"\emph{and} exceeding the larger of the two cells' seed-to-seed sd -- see \S6. "
        r"SAN's PascalVOC-SP row is $\rho_{\text{rel}}=0$ identically for every PE -- "
        r"degenerate, not null (Limitations).}"
    )
    lines.append(r"\label{tab:rho}")
    lines.append(r"\end{table*}")
    return "\n".join(lines)


def build_criterion_b(in_dir):
    """[PER-BACKBONE descriptive + POOLED confirmatory] criterion (b)."""
    lines = [r"% Auto-generated by scripts/make_paper_tables.py -- do not hand-edit.",
             r"% Per-backbone rows are DESCRIPTIVE (n<=5 PEs, underpowered on their own,",
             r"% analysis-plan.md Amendment 3); 'ALL (pooled)' pools every (backbone, PE)",
             r"% arm for that dataset into one Spearman test and is the CONFIRMATORY read.",
             r"\begin{table}[h]", r"\centering\footnotesize",
             r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{llrrr}", r"\toprule",
             r"\textbf{Dataset} & \textbf{Backbone} & \textbf{$n$} & "
             r"\textbf{Spearman $r$} & \textbf{$p$} \\", r"\midrule"]
    for ds in ["peptides-func", "peptides-struct", "pascalvoc-sp"]:
        path = os.path.join(in_dir, f"criterion_b_{ds}.csv")
        if not os.path.exists(path):
            continue
        cdf = pd.read_csv(path)
        for _, row in cdf.iterrows():
            label = (row.backbone if row.backbone == "ALL (pooled)"
                     else BACKBONE_LABEL.get(row.backbone, row.backbone))
            bold = (r"\textbf{%s}" if row.backbone == "ALL (pooled)" else "%s")
            r_str = fmt(row.spearman_r, 2)
            p_str = "--" if pd.isna(row.p) else (f"{row.p:.3g}")
            lines.append(f"{DATASET_LABEL[ds]} & {label} & {int(row.n_pes)} & "
                         f"{bold % r_str} & {p_str} \\\\")
        lines.append(r"\addlinespace")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        r"\caption{Criterion (b): Spearman rank correlation between $\rho_{\text{rel}}$ and "
        r"the task metric (MAE sign-flipped so higher $r$ means ``more local $\Rightarrow$ "
        r"better task''), across each backbone's PE arms, and pooled across all "
        r"(backbone, PE) arms per dataset. Sign and magnitude both differ by backbone.}"
    )
    lines.append(r"\label{tab:critb}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def build_coverage_note(df):
    """[COUNTS ONLY] how much of the nominal 3x5x3 grid actually has data -- for
    Limitations. Counts (backbone, pe, dataset) CELLS with >=1 seed, not seeds."""
    backbones = ["gps", "graphormer", "san"]
    pes = ["none", "lappe", "rwse", "signnet", "grpe"]
    datasets = ["peptides-func", "peptides-struct", "pascalvoc-sp"]
    have = set(zip(df.backbone, df.pe, df.dataset))
    total = len(backbones) * len(pes) * len(datasets)
    got = len(have)
    missing = [
        (b, p, d) for b in backbones for p in pes for d in datasets
        if (b, p, d) not in have
    ]
    lines = [f"% cells present: {got}/{total}", "% missing (backbone, pe, dataset):"]
    for m in missing:
        lines.append(f"%   {m}")
    full_seed = ((df.n_seeds >= 3).sum(), len(df))
    lines.append(f"% cells with 3/3 seeds: {full_seed[0]}/{full_seed[1]}")
    return "\n".join(lines)


def build_headline_summary(in_dir):
    """[DISTILLATION, ONE ROW PER (dataset, backbone)] The single artifact meant
    to carry the paper's headline claim on its own: does this backbone agree with
    the others on PE ranking (Kendall's W, a DATASET-level number, repeated across
    that dataset's backbone rows) and which way does its own sensitivity-vs-task
    correlation point (a BACKBONE-level sign, from criterion_b). Two different
    granularities in one table on purpose -- it is meant to be read as "W says
    backbones agree on ranking; sign says they disagree on what the ranking
    means" in a single glance, not as a third independent statistic."""
    kw_path = os.path.join(in_dir, "kendall_w.csv")
    if not os.path.exists(kw_path):
        return None
    kw = pd.read_csv(kw_path).set_index("dataset")

    sign_by = {}
    for ds in ["peptides-func", "peptides-struct", "pascalvoc-sp"]:
        cb_path = os.path.join(in_dir, f"criterion_b_{ds}.csv")
        if not os.path.exists(cb_path):
            continue
        cb = pd.read_csv(cb_path)
        for _, row in cb.iterrows():
            if row.backbone == "ALL (pooled)":
                continue
            sign_by[(ds, row.backbone)] = row.spearman_r

    lines = [r"% Auto-generated by scripts/make_paper_tables.py -- do not hand-edit.",
             r"% W is a DATASET-level number (repeated per backbone row on purpose --",
             r"% it is a property of how the backbones agree, not of one backbone);",
             r"% correlation sign is a BACKBONE-level number (from criterion_b_*.csv).",
             r"\begin{table}[h]", r"\centering\footnotesize",
             r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{llcc}", r"\toprule",
             r"\textbf{Dataset} & \textbf{Backbone} & \textbf{Rank-agr.\ ($W$)} & "
             r"\textbf{Corr.\ sign} \\", r"\midrule"]
    for ds in ["peptides-func", "peptides-struct", "pascalvoc-sp"]:
        w_row = kw.loc[ds] if ds in kw.index else None
        w_str = "n/a" if (w_row is None or pd.isna(w_row.get("W"))) else f"{w_row['W']:.2f}"
        for backbone in ["gps", "graphormer", "san"]:
            r = sign_by.get((ds, backbone))
            if r is None:
                sign_str = "n/a"
            elif pd.isna(r):
                sign_str = "n/a (degenerate)"
            else:
                sign_str = f"${'+' if r > 0 else ('-' if r < 0 else '0')}$ ({r:.2f})"
            lines.append(f"{DATASET_LABEL[ds]} & {BACKBONE_LABEL[backbone]} & {w_str} & {sign_str} \\\\")
        lines.append(r"\addlinespace[1pt]")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        r"\caption{Headline claim, distilled. \textbf{Rank-agr.\ ($W$)}: Kendall's "
        r"coefficient of concordance between backbones' $\rho_{\text{rel}}$ rankings of "
        r"PEs on that dataset (\S5.2) -- a property of the dataset, "
        r"identical across its backbone rows here. \textbf{Corr.\ sign}: sign of that "
        r"backbone's own Spearman $r$ between $\rho_{\text{rel}}$ and task metric "
        r"(Table~\ref{tab:critb}) -- a property of the backbone. High $W$ with disagreeing "
        r"signs (Peptides-struct) is the paper's central finding: backbones agree which "
        r"PE is more local, not on what that locality means for the task.}"
    )
    lines.append(r"\label{tab:headline}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def build_kendall_table(in_dir):
    """[PER-DATASET, BACKBONES POOLED] Kendall's W over the PE set common to
    every non-degenerate backbone on that dataset. Descriptive numbers only --
    see scripts/make_ranking_figures.py's docstring for the exact procedure."""
    path = os.path.join(in_dir, "kendall_w.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path)
    lines = [r"% Auto-generated by scripts/make_paper_tables.py -- do not hand-edit.",
             r"% W over the PE set common to every backbone with a non-degenerate",
             r"% ranking on that dataset (scripts/make_ranking_figures.py); backbones",
             r"% that never ran a given dataset, or whose rho_rel is degenerate (SAN",
             r"% on PascalVOC-SP), are excluded rather than silently contributing a",
             r"% tied or missing rater.",
             r"\begin{table}[h]", r"\centering\small",
             r"\begin{tabular}{lp{0.2\textwidth}rr}", r"\toprule",
             r"\textbf{Dataset} & \textbf{Backbones (PE set)} & \textbf{Kendall's $W$} & \textbf{$p$} \\",
             r"\midrule"]
    for _, row in df.iterrows():
        if pd.isna(row.W):
            lines.append(f"{DATASET_LABEL[row.dataset]} & {row.note} & -- & -- \\\\")
        else:
            backbones = ", ".join(BACKBONE_LABEL.get(b, b) for b in row.backbones.split(","))
            lines.append(f"{DATASET_LABEL[row.dataset]} & {backbones} ({int(row.n_pe_common)} PEs) & "
                         f"{row.W:.2f} & {row.p:.3g} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\caption{Kendall's coefficient of concordance $W$ (0 = no agreement, "
              r"1 = identical rankings) between backbones' rankings of PEs by "
              r"$\rho_{\text{rel}}$ alone -- a different question from whether "
              r"$\rho_{\text{rel}}$ predicts task performance (Table~\ref{tab:critb}).}",
              r"\label{tab:kendall}", r"\end{table}"]
    return "\n".join(lines)


def build_paired_table(in_dir):
    """[PAIRED, GRAPH-CLUSTERED, SEEDS PRE-AVERAGED PER GRAPH] scripts/paired_bootstrap.py's
    output -- every PE vs. that (backbone, dataset)'s own No-PE arm."""
    path = os.path.join(in_dir, "paired_bootstrap.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path)
    lines = [r"% Auto-generated by scripts/make_paper_tables.py -- do not hand-edit.",
             r"% mean_diff = mean over graphs common to both arms of",
             r"% [rho_rel(PE, g) - rho_rel(None, g)], each side pre-averaged over that",
             r"% arm's own seeds for graph g; CI is a bootstrap over graph identity.",
             r"% CAVEAT (see Limitations): this resamples GRAPHS, not SEEDS -- on a",
             r"% cell where between-seed variance dominates (documented for GraphGPS's",
             r"% PascalVOC-SP arm, findings_gps.txt Sec.8) this CI can be too narrow,",
             r"% the same failure mode as the marginal CIs in Table 3.",
             r"\begin{table*}[t]", r"\centering\small",
             r"\begin{tabular}{llrrrc}", r"\toprule",
             r"\textbf{Dataset} & \textbf{Backbone} & \textbf{PE} & \textbf{$n$ paired graphs} & "
             r"\textbf{$\Delta\rho_{\text{rel}}$ vs.\ No-PE [95\% CI]} & \textbf{sig.} \\",
             r"\midrule"]
    for ds in ["peptides-func", "peptides-struct", "pascalvoc-sp"]:
        sub = df[df.dataset == ds]
        if sub.empty:
            continue
        for backbone in ["gps", "graphormer", "san"]:
            bsub = sub[sub.backbone == backbone].sort_values("pe")
            for _, row in bsub.iterrows():
                sig = r"$\checkmark$" if row.significant else "--"
                lines.append(
                    f"{DATASET_LABEL[ds]} & {BACKBONE_LABEL[backbone]} & {PE_LABEL[row.pe]} & "
                    f"{int(row.n_paired_graphs)} & {fmt(row.mean_diff_rho_rel_vs_none)} "
                    f"[{fmt(row.ci_lo)}, {fmt(row.ci_hi)}] & {sig} \\\\"
                )
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\caption{Paired bootstrap: $\Delta\rho_{\text{rel}}$ of each PE relative to "
              r"that backbone's own No-PE arm, matched by graph identity (not the marginal "
              r"comparison of Table~\ref{tab:results}). SAN's PascalVOC-SP rows are "
              r"identically 0 because $\rho_{\text{rel}}=0$ for every arm there (\S3); "
              r"GraphGPS's PascalVOC-SP rows should be read with the seed-variance caveat "
              r"in \S6/Limitations.}",
              r"\label{tab:paired}", r"\end{table*}"]
    return "\n".join(lines)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--in-dir", default="results_all")
    ap.add_argument("--out-dir", default=".",
                    help="where to write results_tables.tex / results_critb.tex, so "
                         "paper_ACL_format.tex's \\input{results_tables} etc. resolve; "
                         "pass the directory containing the .tex paper")
    ap.add_argument("--log-out", default="results_all/paper_fragments.tex",
                    help="human-readable copy of both tables plus the coverage note")
    args = ap.parse_args()

    df = pd.read_csv(os.path.join(args.in_dir, "summary_table.csv"))
    metric_table = build_metric_table(df)
    rho_table = build_rho_table(df)
    critb_table = build_criterion_b(args.in_dir)
    coverage = build_coverage_note(df)
    kendall_table = build_kendall_table(args.in_dir)
    paired_table = build_paired_table(args.in_dir)
    headline_table = build_headline_summary(args.in_dir)

    with open(os.path.join(args.out_dir, "results_tables.tex"), "w") as f:
        f.write(metric_table + "\n")
    with open(os.path.join(args.out_dir, "results_rho.tex"), "w") as f:
        f.write(rho_table + "\n")
    with open(os.path.join(args.out_dir, "results_critb.tex"), "w") as f:
        f.write(critb_table + "\n")
    parts = [coverage, metric_table, rho_table, critb_table]
    if kendall_table:
        with open(os.path.join(args.out_dir, "results_kendall.tex"), "w") as f:
            f.write(kendall_table + "\n")
        parts.append(kendall_table)
    if paired_table:
        with open(os.path.join(args.out_dir, "results_paired.tex"), "w") as f:
            f.write(paired_table + "\n")
        parts.append(paired_table)
    if headline_table:
        with open(os.path.join(args.out_dir, "results_headline.tex"), "w") as f:
            f.write(headline_table + "\n")
        parts.append(headline_table)
    with open(args.log_out, "w") as f:
        f.write("\n\n".join(parts) + "\n")
    print(f"Wrote {args.out_dir}/results_tables.tex, {args.out_dir}/results_rho.tex, "
          f"{args.out_dir}/results_critb.tex, {args.out_dir}/results_kendall.tex, "
          f"{args.out_dir}/results_paired.tex, {args.out_dir}/results_headline.tex, "
          f"{args.log_out}")
